export const ErrorCode = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  TOKEN_REQUIRED: "TOKEN_REQUIRED",
  INVALID_TOKEN: "INVALID_TOKEN",
  ROLE_MISMATCH: "ROLE_MISMATCH",
  PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
  WALLET_NOT_FOUND: "WALLET_NOT_FOUND",
  WALLET_ALREADY_EXISTS: "WALLET_ALREADY_EXISTS",
  WALLET_DEPOSIT_INVALID: "WALLET_DEPOSIT_INVALID",
  WALLET_INSUFFICIENT_BALANCE: "WALLET_INSUFFICIENT_BALANCE",
  EMAIL_ALREADY_USED: "EMAIL_ALREADY_USED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  INSUFFICIENT_STOCK: "INSUFFICIENT_STOCK",
  INSUFFICIENT_BALANCE: "INSUFFICIENT_BALANCE",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
